name: feedback-board-ui ci/cd
on: workflow_dispatch
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js latest version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js latest version
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Deploy sls
        run: |
          echo "Starting the deployment process..."
          npm run build
